### ISSUE TITLE
Set config in sublime

### ISSUE THREAD

**Issue by hibangun** [markalfred/SublimeLinter-contrib-stylint#7]
Where we can set config stylint in Sublime?

I wanna ignore missing colon, etc

**Comment by markalfred** [comment]
@hibangun please see the [Settings](https://github.com/markalfred/SublimeLinter-contrib-stylint#settings) section of the Readme. In short, you should configure this plugin the same way you'd configure the `stylint` command: via a `.stylintrc` file.
